# Generated by Django 4.2.7 on 2023-11-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_city_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=2),
        ),
    ]
