# Generated by Django 4.2.7 on 2023-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health')], max_length=2),
        ),
    ]
