# Generated by Django 4.2.7 on 2023-11-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_payment_paid_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
