# Generated by Django 4.2.7 on 2023-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_main_image_specialoffer_mains_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('OG', 'Organic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('OG', 'Organic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('OG', 'Organic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care')], max_length=2),
        ),
    ]
