# Generated by Django 4.2.7 on 2023-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product1_delete_product2_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care')], max_length=2),
        ),
    ]
