# Generated by Django 4.2.7 on 2023-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_popular_delete_product1_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_sale', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=255)),
                ('reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SH', 'Sexual health'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('PC', 'Personal Care')], max_length=2)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('thumb1', models.ImageField(upload_to='product_images/')),
                ('thumb2', models.ImageField(upload_to='product_images/')),
                ('thumb3', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Popular',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('PC', 'Personal Care')], max_length=2),
        ),
    ]
