# Generated by Django 4.2.7 on 2023-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_popularproduct_product1_delete_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popularproduct',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
    ]
