# Generated by Django 4.2.7 on 2023-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PopularProduct',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
    ]
