# Generated by Django 4.2.7 on 2023-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_blogpost_delete_popularproduct_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
    ]
