# Generated by Django 4.2.7 on 2023-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=2),
        ),
    ]
