# Generated by Django 4.2.7 on 2023-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health')], max_length=2),
        ),
    ]
