# Generated by Django 4.2.7 on 2023-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_product_images_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=2),
        ),
    ]
