# Generated by Django 4.2.7 on 2023-12-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0042_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post1')),
            ],
        ),
    ]
