# Generated by Django 4.2.7 on 2023-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujrat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health')], max_length=2),
        ),
    ]
