# Generated by Django 4.2.7 on 2023-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_product_wishlist_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
    ]
