# Generated by Django 4.2.7 on 2023-12-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_products_wishlist_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
    ]
