# Generated by Django 4.2.7 on 2023-12-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0046_client_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
