# Generated by Django 4.2.7 on 2023-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
