# Generated by Django 4.2.7 on 2023-12-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_range',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='app.product')),
            ],
        ),
    ]
