# Generated by Django 4.2.7 on 2023-12-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_product_rating_range_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_range',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
