# Generated by Django 4.2.7 on 2023-12-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0050_remove_product_rating_range_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('subject', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
