# Generated by Django 4.2.7 on 2023-12-14 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0051_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
