# Generated by Django 4.2.7 on 2023-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_productreview_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
