# Generated by Django 4.2.7 on 2023-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
    ]
