# Generated by Django 4.2.7 on 2023-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
    ]
