# Generated by Django 4.2.7 on 2023-12-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
    ]
