# Generated by Django 4.2.7 on 2023-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_product_discount_percentage_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('IH', 'Immune Health')], max_length=2),
        ),
    ]
