# Generated by Django 4.2.7 on 2023-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
    ]
