# Generated by Django 4.2.7 on 2023-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('IH', 'Immune Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=2),
        ),
    ]
