# Generated by Django 4.2.7 on 2023-12-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
    ]
