# Generated by Django 4.2.7 on 2023-12-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic')], max_length=2),
        ),
    ]
