# Generated by Django 4.2.7 on 2023-12-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_shop_custom_category_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='custom_category',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Chattisgarh', 'Chattisgarh'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals')], max_length=2),
        ),
    ]
