# Generated by Django 4.2.7 on 2023-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_shop_custom_category_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
    ]
