# Generated by Django 4.2.7 on 2023-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='gift_voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='rewards_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='store_wallet_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gift_voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rewards_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='store_wallet_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
    ]
