# Generated by Django 4.2.7 on 2023-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_orderplaced_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='gift_voucher_code',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='rewards_points',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='store_wallet_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gift_voucher_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rewards_points',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='store_wallet_amount',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=2),
        ),
    ]
