# Generated by Django 4.2.7 on 2023-12-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_remove_orderplaced_coupon_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health')], max_length=2),
        ),
    ]
