# Generated by Django 4.2.7 on 2023-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_coupon_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=2),
        ),
    ]
