# Generated by Django 4.2.7 on 2023-12-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coupon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic')], max_length=2),
        ),
    ]
