# Generated by Django 4.2.7 on 2023-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_rename_discount_percentage_coupon_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('GH', 'General Health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('GH', 'General Health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('GH', 'General Health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('GH', 'General Health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('GH', 'General Health'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
    ]
