# Generated by Django 4.2.7 on 2023-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Pending', 'Pending'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('SH', 'Sexual health')], max_length=2),
        ),
    ]
