# Generated by Django 4.2.7 on 2023-12-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0075_coupon_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField(default=0)),
                ('minimum_order_value', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='rewards_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='store_wallet_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health')], max_length=2),
        ),
        migrations.CreateModel(
            name='StoreWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='gift_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.giftvoucher'),
        ),
    ]
