# Generated by Django 4.2.7 on 2023-12-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_giftvoucher_orderplaced_rewards_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health')], max_length=2),
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_url', models.URLField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='SMSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_url', models.URLField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('courier_name', models.CharField(max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
    ]
