# Generated by Django 4.2.7 on 2023-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_deliverypartner_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPartner',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippinglabel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='order',
        ),
        migrations.RemoveField(
            model_name='whatsappchat',
            name='order',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.DeleteModel(
            name='EmailAlert',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShippingLabel',
        ),
        migrations.DeleteModel(
            name='SMSAlert',
        ),
        migrations.DeleteModel(
            name='WhatsAppChat',
        ),
    ]
