# Generated by Django 4.2.7 on 2023-12-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_delete_deliverypartner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Anti stress'), ('AN', 'Skin Care'), ('AN', 'Herbal Care'), ('OG', 'Organic'), ('D3', 'Vitamin D3'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Anti stress'), ('AN', 'Skin Care'), ('AN', 'Herbal Care'), ('OG', 'Organic'), ('D3', 'Vitamin D3'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Anti stress'), ('AN', 'Skin Care'), ('AN', 'Herbal Care'), ('OG', 'Organic'), ('D3', 'Vitamin D3'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Anti stress'), ('AN', 'Skin Care'), ('AN', 'Herbal Care'), ('OG', 'Organic'), ('D3', 'Vitamin D3'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('AN', 'Anti stress'), ('AN', 'Skin Care'), ('AN', 'Herbal Care'), ('OG', 'Organic'), ('D3', 'Vitamin D3'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
    ]
