# Generated by Django 4.2.7 on 2024-01-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_deliverypartner_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pincode'),
        ),
    ]
