# Generated by Django 4.2.7 on 2024-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_orderplaced_pincode_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
    ]
