# Generated by Django 4.2.7 on 2024-01-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_remove_orderplaced_pincode_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocalDeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Gujrat', 'Gujrat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.courier'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='local_delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.localdeliverypartner'),
        ),
    ]
