# Generated by Django 4.2.7 on 2024-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_courier_localdeliverypartner_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='local_delivery_partner',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='LocalDeliveryPartner',
        ),
    ]
