# Generated by Django 4.2.7 on 2024-01-03 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0085_remove_orderplaced_courier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.CreateModel(
            name='VendorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automated_shipping', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
    ]
