# Generated by Django 4.2.7 on 2024-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_courier_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.RemoveField(
            model_name='vendorfeatures',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DS', 'Dry Skin'), ('PS', 'Poor Sleep'), ('OG', 'Organic'), ('BS', 'Blood Sugar'), ('AD', 'Acidity'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('CP', 'Constipation'), ('C', 'Vitamin C'), ('DD', 'Dandruff'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('PD', 'PCOD'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AC', 'Acne')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DS', 'Dry Skin'), ('PS', 'Poor Sleep'), ('OG', 'Organic'), ('BS', 'Blood Sugar'), ('AD', 'Acidity'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('CP', 'Constipation'), ('C', 'Vitamin C'), ('DD', 'Dandruff'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('PD', 'PCOD'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AC', 'Acne')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DS', 'Dry Skin'), ('PS', 'Poor Sleep'), ('OG', 'Organic'), ('BS', 'Blood Sugar'), ('AD', 'Acidity'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('CP', 'Constipation'), ('C', 'Vitamin C'), ('DD', 'Dandruff'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('PD', 'PCOD'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AC', 'Acne')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DS', 'Dry Skin'), ('PS', 'Poor Sleep'), ('OG', 'Organic'), ('BS', 'Blood Sugar'), ('AD', 'Acidity'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('CP', 'Constipation'), ('C', 'Vitamin C'), ('DD', 'Dandruff'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('PD', 'PCOD'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AC', 'Acne')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('DS', 'Dry Skin'), ('PS', 'Poor Sleep'), ('OG', 'Organic'), ('BS', 'Blood Sugar'), ('AD', 'Acidity'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('CP', 'Constipation'), ('C', 'Vitamin C'), ('DD', 'Dandruff'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('PD', 'PCOD'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AC', 'Acne')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='VendorFeatures',
        ),
    ]
