# Generated by Django 4.2.7 on 2024-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_delete_courier_remove_vendorfeatures_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Gujrat', 'Gujrat'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('CP', 'Constipation'), ('BS', 'Blood Sugar'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AD', 'Acidity'), ('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AC', 'Acne'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('D3', 'Vitamin D3'), ('PD', 'PCOD'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('PS', 'Poor Sleep'), ('A', 'Vitamin A'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('CP', 'Constipation'), ('BS', 'Blood Sugar'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AD', 'Acidity'), ('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AC', 'Acne'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('D3', 'Vitamin D3'), ('PD', 'PCOD'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('PS', 'Poor Sleep'), ('A', 'Vitamin A'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('CP', 'Constipation'), ('BS', 'Blood Sugar'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AD', 'Acidity'), ('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AC', 'Acne'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('D3', 'Vitamin D3'), ('PD', 'PCOD'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('PS', 'Poor Sleep'), ('A', 'Vitamin A'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('CP', 'Constipation'), ('BS', 'Blood Sugar'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AD', 'Acidity'), ('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AC', 'Acne'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('D3', 'Vitamin D3'), ('PD', 'PCOD'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('PS', 'Poor Sleep'), ('A', 'Vitamin A'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('CP', 'Constipation'), ('BS', 'Blood Sugar'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('AD', 'Acidity'), ('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AC', 'Acne'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('D3', 'Vitamin D3'), ('PD', 'PCOD'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('PS', 'Poor Sleep'), ('A', 'Vitamin A'), ('PC', 'Personal Care')], max_length=3),
        ),
    ]
