# Generated by Django 4.2.7 on 2024-01-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AD', 'Acidity'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('PD', 'PCOD'), ('AV', 'Ayurvedic'), ('PS', 'Poor Sleep'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('CP', 'Constipation'), ('B12', 'Vitamin B12'), ('AC', 'Acne'), ('GH', 'General Health'), ('BS', 'Blood Sugar'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AD', 'Acidity'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('PD', 'PCOD'), ('AV', 'Ayurvedic'), ('PS', 'Poor Sleep'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('CP', 'Constipation'), ('B12', 'Vitamin B12'), ('AC', 'Acne'), ('GH', 'General Health'), ('BS', 'Blood Sugar'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AD', 'Acidity'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('PD', 'PCOD'), ('AV', 'Ayurvedic'), ('PS', 'Poor Sleep'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('CP', 'Constipation'), ('B12', 'Vitamin B12'), ('AC', 'Acne'), ('GH', 'General Health'), ('BS', 'Blood Sugar'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AD', 'Acidity'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('PD', 'PCOD'), ('AV', 'Ayurvedic'), ('PS', 'Poor Sleep'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('CP', 'Constipation'), ('B12', 'Vitamin B12'), ('AC', 'Acne'), ('GH', 'General Health'), ('BS', 'Blood Sugar'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AD', 'Acidity'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('DD', 'Dandruff'), ('DS', 'Dry Skin'), ('PD', 'PCOD'), ('AV', 'Ayurvedic'), ('PS', 'Poor Sleep'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('CP', 'Constipation'), ('B12', 'Vitamin B12'), ('AC', 'Acne'), ('GH', 'General Health'), ('BS', 'Blood Sugar'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AN', 'Antioxidants')], max_length=3),
        ),
    ]
