# Generated by Django 4.2.7 on 2024-01-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_client_email_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('BS', 'Blood Sugar'), ('PD', 'PCOD'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('DS', 'Dry Skin'), ('AC', 'Acne'), ('WH', 'Women health'), ('CP', 'Constipation'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('DD', 'Dandruff'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('PS', 'Poor Sleep'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('AD', 'Acidity'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('BS', 'Blood Sugar'), ('PD', 'PCOD'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('DS', 'Dry Skin'), ('AC', 'Acne'), ('WH', 'Women health'), ('CP', 'Constipation'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('DD', 'Dandruff'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('PS', 'Poor Sleep'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('AD', 'Acidity'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('BS', 'Blood Sugar'), ('PD', 'PCOD'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('DS', 'Dry Skin'), ('AC', 'Acne'), ('WH', 'Women health'), ('CP', 'Constipation'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('DD', 'Dandruff'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('PS', 'Poor Sleep'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('AD', 'Acidity'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('BS', 'Blood Sugar'), ('PD', 'PCOD'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('DS', 'Dry Skin'), ('AC', 'Acne'), ('WH', 'Women health'), ('CP', 'Constipation'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('DD', 'Dandruff'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('PS', 'Poor Sleep'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('AD', 'Acidity'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('BS', 'Blood Sugar'), ('PD', 'PCOD'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('DS', 'Dry Skin'), ('AC', 'Acne'), ('WH', 'Women health'), ('CP', 'Constipation'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('DD', 'Dandruff'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('PS', 'Poor Sleep'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('AD', 'Acidity'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health')], max_length=3),
        ),
    ]
