# Generated by Django 4.2.7 on 2024-01-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.deliverypartner'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='email_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='local_delivery_partner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='manual_courier_tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='shipping_label',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shippinglabel'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='sms_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='whatsapp_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.whatsappchat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced'),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='whatsappchat',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced'),
        ),
    ]
