# Generated by Django 4.2.7 on 2024-01-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_orderplaced_delivery_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_partner',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='email_alert_sent',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='local_delivery_partner',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='manual_courier_tracking',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='shipping_label',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='sms_alert_sent',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='whatsapp_chat',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced'),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='whatsappchat',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced'),
        ),
    ]
