# Generated by Django 4.2.7 on 2024-01-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.orderplaced'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health')], max_length=3),
        ),
    ]
