# Generated by Django 4.2.7 on 2024-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_remove_payment_order_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic')], max_length=3),
        ),
    ]
