# Generated by Django 4.2.7 on 2024-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=3),
        ),
    ]
