# Generated by Django 4.2.7 on 2024-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('SH', 'Sexual health')], max_length=3),
        ),
    ]
