# Generated by Django 4.2.7 on 2024-01-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_payment_order_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic')], max_length=3),
        ),
    ]
