# Generated by Django 4.2.7 on 2024-01-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic')], max_length=3),
        ),
    ]
