# Generated by Django 4.2.7 on 2024-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_remove_payment_order_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('MH', 'Men Health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K')], max_length=3),
        ),
    ]
