# Generated by Django 4.2.7 on 2024-01-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
    ]
