# Generated by Django 4.2.7 on 2024-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health')], max_length=3),
        ),
    ]
