# Generated by Django 4.2.7 on 2024-01-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderplaced')),
            ],
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='status_updates',
            field=models.ManyToManyField(blank=True, to='app.orderstatusupdate'),
        ),
    ]
