# Generated by Django 4.2.7 on 2024-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('E', 'Vitamin E')], max_length=3),
        ),
    ]
