# Generated by Django 4.2.7 on 2024-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='status_updates',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.DeleteModel(
            name='OrderStatusUpdate',
        ),
    ]
