# Generated by Django 4.2.7 on 2024-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_remove_orderplaced_status_updates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health')], max_length=3),
        ),
    ]
