# Generated by Django 4.2.7 on 2024-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_shippingcharge_customer_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingCharge',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_pincode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('IH', 'Immune Health')], max_length=3),
        ),
    ]
