# Generated by Django 4.2.7 on 2024-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_pincode_delete_shippingcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('WH', 'Women health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('OG', 'Organic'), ('E', 'Vitamin E')], max_length=3),
        ),
    ]
