# Generated by Django 4.2.7 on 2024-01-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_shippingcharge_delete_pincode_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('stock_status', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packs', to='app.product')),
            ],
        ),
    ]
