# Generated by Django 4.2.7 on 2024-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('VM', 'Vitamins&Minerals'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ProductPack',
        ),
    ]
