# Generated by Django 4.2.7 on 2024-01-08 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
    ]
