# Generated by Django 4.2.7 on 2024-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ProductPack',
        ),
    ]
