# Generated by Django 4.2.7 on 2024-01-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('MH', 'Men Health'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('MH', 'Men Health'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('MH', 'Men Health'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('MH', 'Men Health'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('WH', 'Women health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('MH', 'Men Health'), ('D3', 'Vitamin D3'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
        ),
    ]
