# Generated by Django 4.2.7 on 2024-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('MH', 'Men Health'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
