# Generated by Django 4.2.7 on 2024-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsulePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('OG', 'Organic'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health')], max_length=3),
        ),
    ]
