# Generated by Django 4.2.7 on 2024-01-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_capsulepack_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapsulePack',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('B12', 'Vitamin B12'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('C', 'Vitamin C'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('AN', 'Antioxidants')], max_length=3),
        ),
    ]
