# Generated by Django 4.2.7 on 2024-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_delete_capsulepack_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricedrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('price_drop_percentage', models.FloatField()),
                ('sale_end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
    ]
