# Generated by Django 4.2.7 on 2024-01-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('IH', 'Immune Health'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K')], max_length=3),
        ),
    ]
