# Generated by Django 4.2.7 on 2024-01-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic')], max_length=3),
        ),
    ]
