# Generated by Django 4.2.7 on 2024-01-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('GH', 'General Health'), ('WH', 'Women health'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('VM', 'Vitamins&Minerals'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('B12', 'Vitamin B12')], max_length=3),
        ),
    ]
