# Generated by Django 4.2.7 on 2024-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('E', 'Vitamin E'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('C', 'Vitamin C')], max_length=3),
        ),
    ]
