# Generated by Django 4.2.7 on 2024-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('B12', 'Vitamin B12'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('K', 'Vitamin K'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3')], max_length=3),
        ),
    ]
