# Generated by Django 4.2.7 on 2024-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('E', 'Vitamin E'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('E', 'Vitamin E'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('E', 'Vitamin E'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('E', 'Vitamin E'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('IH', 'Immune Health'), ('E', 'Vitamin E'), ('OG', 'Organic'), ('MH', 'Men Health'), ('C', 'Vitamin C'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('A', 'Vitamin A'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements')], max_length=3),
        ),
    ]
