# Generated by Django 4.2.7 on 2024-01-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_product_packname_product_stock_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packname',
        ),
        migrations.AddField(
            model_name='product',
            name='packtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'packed'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=3),
        ),
    ]
