# Generated by Django 4.2.7 on 2024-01-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_remove_product_packname_product_packtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packtitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'packed'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('WH', 'Women health'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('PC', 'Personal Care')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('stock_status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
