# Generated by Django 4.2.7 on 2024-01-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_remove_product_packtitle_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='pack_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pack_sizes', to='app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_sizes', to='app.product'),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('OG', 'Organic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('D3', 'Vitamin D3'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('OG', 'Organic')], max_length=3),
        ),
    ]
