# Generated by Django 4.2.7 on 2024-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_productsize_pack_product_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AV', 'Ayurvedic'), ('K', 'Vitamin K'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('DH', 'Digestive Health'), ('D3', 'Vitamin D3'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('WH', 'Women health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
