# Generated by Django 4.2.7 on 2024-01-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('WH', 'Women health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('WH', 'Women health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('WH', 'Women health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('WH', 'Women health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('K', 'Vitamin K'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('WH', 'Women health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C')], max_length=3),
        ),
    ]
