# Generated by Django 4.2.7 on 2024-01-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('OG', 'Organic'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('E', 'Vitamin E'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('AV', 'Ayurvedic'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health')], max_length=3),
        ),
    ]
