# Generated by Django 4.2.7 on 2024-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('OG', 'Organic'), ('A', 'Vitamin A'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('B12', 'Vitamin B12'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('E', 'Vitamin E')], max_length=3),
        ),
    ]
