# Generated by Django 4.2.7 on 2024-01-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0143_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('GH', 'General Health'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('A', 'Vitamin A'), ('K', 'Vitamin K'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
    ]
