# Generated by Django 4.2.7 on 2024-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_product_descriptions_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('MH', 'Men Health'), ('OG', 'Organic'), ('IH', 'Immune Health'), ('A', 'Vitamin A'), ('AN', 'Antioxidants'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('GH', 'General Health')], max_length=3),
        ),
    ]
