# Generated by Django 4.2.7 on 2024-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='product',
            name='new_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('A', 'Vitamin A'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('E', 'Vitamin E'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('GH', 'General Health')], max_length=3),
        ),
    ]
