# Generated by Django 4.2.7 on 2024-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_remove_product_descriptions_product_new_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_field',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('GH', 'General Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('K', 'Vitamin K'), ('WH', 'Women health'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('E', 'Vitamin E'), ('AN', 'Antioxidants'), ('B12', 'Vitamin B12'), ('A', 'Vitamin A'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('GH', 'General Health')], max_length=3),
        ),
    ]
