# Generated by Django 4.2.7 on 2024-01-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Daman and Diu', 'Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('OG', 'Organic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('OG', 'Organic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('OG', 'Organic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('OG', 'Organic'), ('K', 'Vitamin K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('SH', 'Sexual health'), ('C', 'Vitamin C'), ('GH', 'General Health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('B12', 'Vitamin B12'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('D3', 'Vitamin D3'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('OG', 'Organic'), ('K', 'Vitamin K')], max_length=3),
        ),
    ]
