# Generated by Django 4.2.7 on 2024-01-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('C', 'Vitamin C'), ('B12', 'Vitamin B12'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('A', 'Vitamin A')], max_length=3),
        ),
    ]
