# Generated by Django 5.0.1 on 2024-01-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0150_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('A', 'Vitamin A'), ('D3', 'Vitamin D3'), ('C', 'Vitamin C'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('K', 'Vitamin K'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=3),
        ),
    ]
