# Generated by Django 5.0.1 on 2024-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('C', 'Vitamin C'), ('A', 'Vitamin A'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3')], max_length=3),
        ),
    ]
