# Generated by Django 4.2.7 on 2024-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('A', 'Vitamin A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('SH', 'Sexual health'), ('MH', 'Men Health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('E', 'Vitamin E'), ('PC', 'Personal Care'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('A', 'Vitamin A')], max_length=3),
        ),
    ]
