# Generated by Django 4.2.7 on 2024-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Packed', 'packed'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('OG', 'Organic'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('E', 'Vitamin E'), ('DH', 'Digestive Health'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('C', 'Vitamin C'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('GH', 'General Health'), ('K', 'Vitamin K'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
    ]
