# Generated by Django 4.2.7 on 2024-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_productsize_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='delivery_pincode',
            new_name='delivery_zipcode',
        ),
        migrations.RenameField(
            model_name='shippingcharge',
            old_name='pincode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('MH', 'Men Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('D3', 'Vitamin D3'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('GH', 'General Health'), ('E', 'Vitamin E'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('C', 'Vitamin C'), ('HS', 'Herbal, Specialty Supplements'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('K', 'Vitamin K'), ('MH', 'Men Health')], max_length=3),
        ),
    ]
