# Generated by Django 4.2.7 on 2024-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_delete_productsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='delivery_zipcode',
            new_name='delivery_pincode',
        ),
        migrations.RenameField(
            model_name='shippingcharge',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('C', 'Vitamin C'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('A', 'Vitamin A'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('B12', 'Vitamin B12'), ('D3', 'Vitamin D3'), ('E', 'Vitamin E')], max_length=3),
        ),
    ]
