# Generated by Django 4.2.7 on 2023-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'General Health'), ('AN', 'Antioxidants'), ('PC', 'Personal Care'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('HS', 'Herbal, Specialty Supplements'), ('SH', 'Sexual health'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=2),
        ),
    ]
