# Generated by Django 4.2.7 on 2023-11-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('thumb1', models.ImageField(upload_to='product_images/')),
                ('thumb2', models.ImageField(upload_to='product_images/')),
                ('thumb3', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Haryana', 'Haryana'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('SH', 'Sexual health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('IH', 'Immune Health')], max_length=2),
        ),
    ]
