# Generated by Django 4.2.7 on 2023-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product1_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MH', 'Men Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=2)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('thumb1', models.ImageField(upload_to='product_images/')),
                ('thumb2', models.ImageField(upload_to='product_images/')),
                ('thumb3', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('PC', 'Personal Care'), ('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('VM', 'Vitamins&Minerals'), ('SH', 'Sexual health'), ('WH', 'Women health')], max_length=2),
        ),
    ]
