# Generated by Django 4.2.7 on 2023-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_shop_reviews_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=2)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('IH', 'Immune Health'), ('AN', 'Antioxidants'), ('MH', 'Men Health'), ('AV', 'Ayurvedic'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('HS', 'Herbal, Specialty Supplements'), ('PC', 'Personal Care'), ('WH', 'Women health')], max_length=2),
        ),
    ]
