# Generated by Django 4.2.7 on 2023-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_post_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('WH', 'Women health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('IH', 'Immune Health'), ('MH', 'Men Health'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('AV', 'Ayurvedic'), ('SH', 'Sexual health'), ('HS', 'Herbal, Specialty Supplements'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('WH', 'Women health')], max_length=2),
        ),
    ]
