# Generated by Django 4.2.7 on 2023-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_blogpost_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=2)),
                ('image_url', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Daman and Diu', 'Daman and Diu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('AN', 'Antioxidants'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('OG', 'Organic')], max_length=2),
        ),
    ]
