# Generated by Django 4.2.7 on 2023-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_popular_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialoffer',
            old_name='mains_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='specialoffer',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='thumblist1',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='thumblist2',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='thumblist3',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'packed'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('SH', 'Sexual health'), ('WH', 'Women health'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('AV', 'Ayurvedic'), ('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('OG', 'Organic'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('HS', 'Herbal, Specialty Supplements')], max_length=2),
        ),
    ]
