# Generated by Django 4.2.7 on 2023-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_mains_image_specialoffer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('comments', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Gujrat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Wey', 'On The Way'), ('Packed', 'packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('OG', 'Organic'), ('AN', 'Antioxidants'), ('GH', 'General Health'), ('HS', 'Herbal, Specialty Supplements'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('WH', 'Women health'), ('DH', 'Digestive Health'), ('VM', 'Vitamins&Minerals'), ('PC', 'Personal Care')], max_length=2),
        ),
    ]
