# Generated by Django 4.2.7 on 2023-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_post1_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'packed'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('PC', 'Personal Care')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('SH', 'Sexual health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('WH', 'Women health'), ('VM', 'Vitamins&Minerals'), ('OG', 'Organic'), ('GH', 'General Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('MH', 'Men Health'), ('PC', 'Personal Care')], max_length=2),
        ),
    ]
