# Generated by Django 4.2.7 on 2023-11-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_post1_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujrat', 'Gujrat'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Chattisgarh', 'Chattisgarh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('IH', 'Immune Health'), ('AV', 'Ayurvedic'), ('AN', 'Antioxidants'), ('OG', 'Organic'), ('PC', 'Personal Care'), ('HS', 'Herbal, Specialty Supplements'), ('MH', 'Men Health'), ('VM', 'Vitamins&Minerals'), ('WH', 'Women health'), ('SH', 'Sexual health'), ('GH', 'General Health')], max_length=2),
        ),
    ]
