# Generated by Django 4.2.7 on 2023-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Daman and Diu', 'Daman and Diu'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Wey', 'On The Way')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/thumbnails'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('DH', 'Digestive Health'), ('GH', 'General Health'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('PC', 'Personal Care'), ('VM', 'Vitamins&Minerals'), ('IH', 'Immune Health'), ('MH', 'Men Health'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('WH', 'Women health'), ('AV', 'Ayurvedic')], max_length=2),
        ),
    ]
